#pragma once

#include "process.h"

namespace Client {
	enum LEVEL_STATE { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_END};

    enum PLAYER_STATE {
        PLAYER_IDLE,
        PLAYER_ATTACK_IDLE,
        PLAYER_IDLE_PUT_AWAY,
        PLAYER_RUN_START,
        PLAYER_RUN,
        PLAYER_RUN_STOP,
        PLAYER_SPRINT_START,
        PLAYER_SPRINT,
        PLAYER_SPRINT_TO_RUN,
        PLAYER_SPRINT_STOP,
        PLAYER_ATTACK_1,
        PLAYER_ATTACK_2,
        PLAYER_ATTACK_3,
        PLAYER_ATTACK_4,
        PALYER_ATTACK_SPEC,
        PLAYER_ATTACK_END,
        PLAYER_ELEMENTAL_START,
        PLAYER_ELEMENTAL_1,
        PLAYER_ELEMENTAL_2,
        PLAYER_ELEMENTAL_3,
        PLAYER_ELEMENTAL_SPEC,
        PLAYER_ELEMENTAL_1_END,
        PLAYER_ELEMENTAL_2_END,
        PLAYER_ELEMENTAL_3_END,
        PLAYER_ELEMENTAL_SPEC_END,
        PLAYER_ELEMENTAL_UP_START,
        PLAYER_ELEMENTAL_UP,
        PLAYER_ELEMENTAL_END,
        PLAYER_ELEMENTAL_BURST,
        PLAYER_ELEMENTAL_BURST_END,
        PLAYER_JUMP,
        PLAYER_JUMP_FOR_RUN,
        PLAYER_JUMP_FOR_SPRINT,
        PLAYER_FALL_GROUND_H,
        PLAYER_FALL_GROUND_L,
        PLAYER_FALL_GROUND_FOR_RUN,
        PLAYER_FALL_GROUND_FOR_SPRINT,
        PLAYER_FALL_ATTACK_START,
        PLAYER_FALL_ATTACK_LOOP,
        PLAYER_FALL_ATTACK_END,
        PLAYER_FLY_START,
        PLAYER_FLY_NORMAL,
        PLAYER_FLY_TURN_L,
        PLAYER_FLY_TURN_R,
        PLAYER_HILL_UP,
        PLAYER_HILL_DOWN,
        PLAYER_END
    };

	const unsigned int g_iWinSizeX = 1280;
	const unsigned int g_iWinSizeY = 720;
};

extern HWND g_hWnd;
extern HINSTANCE g_hInst;

using namespace Client;